server:
  port: 3001

spring:
  servlet:
    multipart: # 파일 업로드 설정
      maxFileSize: 5MB
      maxRequestSize: 10MB

  datasource: # 데이터 베이스 연결 설정
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: chatting
    password: _aA123456

  jpa: # JPA 설정
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: update

logging:
  level:
    org:
      hibernate:
        type:
           descriptor:
              sql: trace

# 파일 업로드 경로 설정
file:
  upload:
    path: C:/uploads/
    url: /uploads/
